# Generated by Django 5.2.8 on 2025-11-26 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['enrollment_number'], 'permissions': [('can_toggle_status', 'Can toggle in/out status')]},
        ),
    ]
