# Generated by Django 5.2.8 on 2025-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
